# Generated by Django 2.2.1 on 2019-05-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source',
            field=models.CharField(default='telegram', max_length=20),
        ),
    ]
