# Generated by Django 2.2.1 on 2019-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190521_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
