# Generated by Django 2.2.1 on 2019-05-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deposit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='post_to_spicefeed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_to_spicefeed',
            field=models.BooleanField(default=True),
        ),
    ]
