# Generated by Django 2.2.1 on 2019-06-07 00:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190531_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPagingTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions', models.BigIntegerField(default=1)),
                ('messages', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_user_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
