# Generated by Django 2.2.1 on 2019-06-18 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190618_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='last_privacy_setting',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='post_to_spicefeed',
            field=models.BooleanField(default=True),
        ),
    ]
