# Generated by Django 2.2.1 on 2019-06-20 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190618_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleLegerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_leger_address', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slpAddress', to='main.User')),
            ],
        ),
    ]
