# Generated by Django 2.2.1 on 2019-06-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_simplelegeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelegeraddress',
            name='simple_leger_address',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
