# Generated by Django 2.2.1 on 2019-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190620_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(max_length=64, null=True, blank=True),
        ),
    ]
