# Generated by Django 2.2.1 on 2019-06-21 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_deposit_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleledgeraddress',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
