# Generated by Django 2.2.1 on 2019-06-30 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_media_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=30)),
                ('ga_cookie', models.CharField(max_length=50)),
                ('slp_address', models.CharField(max_length=60)),
                ('transaction_id', models.CharField(blank=True, max_length=70)),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
