# Generated by Django 2.2.1 on 2019-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_faucetdisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucetdisbursement',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
