# Generated by Django 2.2.1 on 2019-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_faucetdisbursement_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucetdisbursement',
            name='ga_cookie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
