# Generated by Django 2.2.1 on 2019-07-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190708_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleledgeraddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slp_addresses', to='main.User'),
        ),
    ]
