# Generated by Django 2.2.1 on 2019-07-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190708_0657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterPagingTracker',
        ),
    ]
