# Generated by Django 2.2.1 on 2019-07-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_twitterpagingtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bitcash_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='simple_ledger_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='wip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
