# Generated by Django 2.2.1 on 2019-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190719_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bitcash_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='simple_ledger_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
