# Generated by Django 2.2.1 on 2019-07-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190719_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='simple_ledger_address',
        ),
    ]
