# Generated by Django 2.2.1 on 2019-07-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_user_simple_ledger_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wip',
            new_name='simple_ledger_address',
        ),
        migrations.AddField(
            model_name='user',
            name='wif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
