# Generated by Django 2.2.1 on 2019-07-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190719_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleLedgerAddress',
        ),
    ]
