# Generated by Django 2.2.1 on 2019-07-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_simpleledgeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bitcash_address',
            new_name='bitcoincash_address',
        ),
    ]
