# Generated by Django 2.2.1 on 2019-07-24 11:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190724_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='recipient_content_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
