# Generated by Django 2.2.1 on 2019-07-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190724_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wif',
        ),
    ]
