# Generated by Django 2.2.1 on 2019-08-14 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190811_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
