# Generated by Django 2.2.1 on 2019-08-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_account'),
        ('main', '0038_auto_20190811_0639'),
    ]

    operations = [
    ]
