# Generated by Django 2.2.1 on 2019-08-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190814_1607'),
        ('main', '0040_user_pof'),
    ]

    operations = [
    ]
