# Generated by Django 2.2.1 on 2019-08-17 02:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_account_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='confirmation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
