# Generated by Django 2.2.1 on 2019-08-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190817_0312'),
        ('main', '0043_merge_20190816_0909'),
    ]

    operations = [
    ]
