# Generated by Django 2.2.1 on 2019-08-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_merge_20190817_0808'),
        ('main', '0044_merge_20190817_1016'),
    ]

    operations = [
    ]
