# Generated by Django 2.2.1 on 2019-08-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_merge_20190817_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pof',
        ),
    ]
