# Generated by Django 2.2.1 on 2019-08-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20190817_0300'),
        ('main', '0047_user_pof'),
    ]

    operations = [
    ]
