#Generated by Django 2.2.1 on 2019-08-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('main', '0048_merge_20190822_1104'),
	]

	operations = [
		migrations.RenameField(
			model_name='account',
			old_name='email_address',
			new_name='email_addr'
		)
	]