# Generated by Django 2.2.1 on 2019-08-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20190822_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]