# Generated by Django 2.2.1 on 2019-08-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20190822_1107'),
        ('main', '0048_deposit_date_swept'),
    ]

    operations = [
    ]
