# Generated by Django 2.2.1 on 2019-08-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_deposit_date_swept'),
        ('main', '0050_auto_20190827_0230'),
    ]

    operations = [
    ]
