# Generated by Django 2.2.1 on 2019-08-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_merge_20190829_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
