# Generated by Django 2.2.1 on 2019-08-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_merge_20190829_0934'),
        ('main', '0051_auto_20190830_0455'),
    ]

    operations = [
    ]
