# Generated by Django 2.2.1 on 2019-09-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190822_0628'),
        ('main', '0052_merge_20190830_2006'),
    ]

    operations = [
    ]
