# Generated by Django 2.2.1 on 2019-09-04 09:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_merge_20190903_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=50)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('botReplied', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='main.User')),
            ],
        ),
    ]
