# Generated by Django 2.2.1 on 2019-09-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='main.Content'),
        ),
    ]
