# Generated by Django 2.2.1 on 2019-09-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20190905_0645'),
        ('main', '0055_auto_20190905_0718'),
    ]

    operations = [
    ]
