# Generated by Django 2.2.1 on 2019-09-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_merge_20190905_0910'),
        ('main', '0053_merge_20190904_0634'),
    ]

    operations = [
    ]
