# Generated by Django 2.2.1 on 2019-09-09 04:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20190906_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
