# Generated by Django 2.2.1 on 2019-09-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20190909_0421'),
        ('main', '0059_auto_20190910_1243'),
    ]

    operations = [
    ]
