# Generated by Django 2.2.1 on 2019-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_merge_20190911_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='chat_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
