# Generated by Django 2.2.1 on 2019-09-26 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20190919_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_amount', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('recepients', models.ManyToManyField(to='main.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='main.User')),
            ],
        ),
    ]
