# Generated by Django 2.2.1 on 2019-09-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_telegramgroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='users',
            field=models.ManyToManyField(related_name='telegramgroups', to='main.User'),
        ),
    ]
