# Generated by Django 2.2.1 on 2019-10-02 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20190927_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
