# Generated by Django 3.2.25 on 2025-11-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20191002_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reddit_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reddit_user_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='simple_ledger_address',
        ),
        migrations.AlterField(
            model_name='account',
            name='confirmation',
            field=models.JSONField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='content',
            name='recipient_content_id',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pof',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_user_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_user_details',
            field=models.JSONField(default=dict),
        ),
    ]
