# Generated by Django 3.2.25 on 2025-12-06 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20251129_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='main.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['chat_id', 'message_id'], name='main_telegr_chat_id_6d20fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegrammessage',
            unique_together={('chat_id', 'message_id')},
        ),
    ]
