# Generated by Django 3.2.25 on 2025-12-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20251206_1709'),
    ]

    operations = [
        # Rename post_to_spicefeed to post_to_chipfeed in all 3 tables
        migrations.RenameField(
            model_name='user',
            old_name='post_to_spicefeed',
            new_name='post_to_chipfeed',
        ),
        migrations.RenameField(
            model_name='telegramgroup',
            old_name='post_to_spicefeed',
            new_name='post_to_chipfeed',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='post_to_spicefeed',
            new_name='post_to_chipfeed',
        ),
    ]
