apiVersion: v1
kind: Service
metadata:
  name: spicebot-prod
  namespace: spicebot-prod
  labels:
    app: spicebot-prod
spec:
  selector:
    app: spicebot-prod
  type: NodePort
  ports:
    - name: backend-prod
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spicebot-prod
  namespace: spicebot-prod
  labels:
    app: spicebot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spicebot-prod
  template:
    metadata:
      labels:
        app: spicebot-prod
    spec:
      containers:
        - name: spicebot
          image: gcr.io/spice-slp-token/spicebot-prod:0.0.144
          env:
            - name: DEPLOYMENT_INSTANCE
              value: prod
            - name: POSTGRES_DB
              value: spicebot-prod
            - name: POSTGRES_HOST
              value: 127.0.0.1
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: hostname
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: port
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: telegrambottoken
            - name: TELEGRAM_BOT_USER
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: telegrambotuser
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: twitterconsumerkey
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: twitterconsumersecret
            - name: TWITTER_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: twitteraccesskey
            - name: TWITTER_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: twitteraccesssecret
            - name: TWITTER_BOT_NAME
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: twitterbotname
            - name: SPICE_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: spicetokenid
            - name: SPICE_FUNDING_SLP_ADDR
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: spicefundingslpaddr
            - name: SPICE_FUNDING_CASH_ADDR
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: spicefundingcashaddr
            - name: SPICE_FUNDING_WIF
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: spicefundingwif
            - name: FAUCET_SLP_ADDR
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: faucetslpaddr
            - name: FAUCET_CASH_ADDR
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: faucetcashaddr
            - name: FAUCET_WIF
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: faucetwif
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: recaptchasecret
            - name: PARENT_XPUBKEY
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: parentxpubkey
            - name: BCH_FEE_FUNDING_SLP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: bchfeefundingslpaddress
            - name: BCH_FEE_FUNDING_CASH_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: bchfeefundingcashaddress
            - name: BCH_FEE_FUNDING_WIF
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: bchfeefundingwif
            - name: REDDIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: redditclientid
            - name: REDDIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: redditclientsecret
            - name: REDDIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: redditusername
            - name: REDDIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: redditpassword
            - name: REDDIT_USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: other-credentials
                  key: reddituseragent
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command:
            [
              "/cloud_sql_proxy",
              "-instances=spice-slp-token:us-central1:spicebot=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
